### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by GoGeChang** [Barrior/JParticles#22]
使用Vue引入
代码：
```
import { Particle } from "jparticles";


 new Particle.WaveLoading('#mainLoad', {
      fillColor: '#27C9E5',
      crestHeight: 5,
      crestCount: 3,
      speed: 0.2,
      // 加载进度文本格式为空字符串时，不显示进度文本
      textFormatter: '',
      // 取消边框圆角
      borderRadius: '',
      // 设置遮罩图片，实现遮罩效果（如果希望防止图片闪烁，可提前加载完图片后再创建特效）
      mask: 'https://raw.githubusercontent.com/Barrior/assets/main/github-logo-text.svg',
  })

```

报错：
`jparticles__WEBPACK_IMPORTED_MODULE_2__.Particle.WaveLoading is not a constructor"`

found in

和

` jparticles__WEBPACK_IMPORTED_MODULE_2__.Particle.WaveLoading is not a constructor`

直接使用
`new Particle('#mainLoad', {
      fillColor: '#27C9E5',
      crestHeight: 5,
      crestCount: 3,
      speed: 0.2,
      // 加载进度文本格式为空字符串时，不显示进度文本
      textFormatter: '',
      // 取消边框圆角
      borderRadius: '',
      // 设置遮罩图片，实现遮罩效果（如果希望防止图片闪烁，可提前加载完图片后再创建特效）
      mask: 'https://raw.githubusercontent.com/Barrior/assets/main/github-logo-text.svg',
  })`

是可以的，但是其他效果都是报错，我网上也查不到相关问题，请作者大大回复下我，谢谢。

**Comment by GoGeChang** [comment]
换句话说，new JParticles.特效名    无效

**Comment by GoGeChang** [comment]
手动下载特效到本地，然后引入把问题解决了，但是问题来了，我加载了我的svg图片，图片被裁剪了，只显示了很小的一部分区域，显示出现了问题

**Comment by Barrior** [comment]
> 换句话说，new JParticles.特效名 无效

上面的代码写错了，不是 `new Particle.WaveLoading`，是 `new JParticles.WaveLoading `，或者像下面这样：
```javascript
import { WaveLoading } from "jparticles";

new WaveLoading('#mainLoad')
```
@GoGeChang

**Comment by Barrior** [comment]
> 手动下载特效到本地，然后引入把问题解决了，但是问题来了，我加载了我的svg图片，图片被裁剪了，只显示了很小的一部分区域，显示出现了问题

是有这个问题，如果 svg 图片没有设置宽高属性，源码里通过 new Image 对象拿不到正确的宽高，因为 svg 是矢量图，所以可以给 svg 图片设置一个很大的宽高，然后就可以解决这个问题了
