### ISSUE TITLE
Next.js Error:  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by muhammadali-pro** [Barrior/JParticles#26]
I have recently used this package for adding particles animation. I used it in React (Next.js) .  i got this error when trying to use it.  

![Screenshot from 2024-01-20 17-57-21](https://github.com/Barrior/JParticles/assets/118300634/eacf2960-85f1-48c5-8797-3f54166aaf6c)

> node_modules/jparticles/lib/common/constants.js (6:31) @ window  ⨯ ReferenceError: window is not defined

**Here is my Next.js Component** 

```
"use client";
import { Particle } from 'jparticles';
import React, { memo, useEffect } from 'react'

const ParticleEffect = () => {
    if(typeof window !== 'undefined')
{
// Your client-side code that uses window goes here
}
    useEffect(()=>{
        new Particle("#demo", {
          color: "#004AAD",
          lineShape: "spider",
          range: 200,
          proximity: 100,
        });
      },[]);
  return (
    typeof window !== 'undefined' &&  <div className="absolute w-full h-3/4" id="demo"></div>
  )
}

export default memo(ParticleEffect);
```

**Comment by Barrior** [comment]
@muhammadali-pro  JParticles does not support SSR, you can use [Dynamic Import External Libraries](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#loading-external-libraries) in Next.js to solve this problem.

```jsx
const ParticleEffect = () => {
  const createParticles = async () => {

    // dynamic import
    const { Particle } = (await import('jparticles')).default

    new Particle('#demo', {
      color: '#004AAD',
      lineShape: 'spider',
      range: 200,
      proximity: 100,
    })
  }

  useEffect(() => {
    createParticles()
  }, [])

  return <div className="absolute w-full h-3/4" id="demo"></div>
}

export default memo(ParticleEffect);
```

Live Demo: [![Edit jparticles-nextjs](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/jparticles-nextjs-s375pc?embed=1&file=%2Fapp%2Fpage.tsx)

**Comment by muhammadali-pro** [comment]
Thank you. I think you can close this issue now.
