### ISSUE TITLE
粒子旋转

### ISSUE THREAD

**Issue by Minamtt** [Barrior/JParticles#27]
能否添加粒子的随机旋转？

**Comment by Barrior** [comment]
> 能否添加粒子的随机旋转？

是在原来 Particle 特效上增加粒子的随机旋转，还是新增一个这样的特效？有效果图吗，简易版的也行，我瞅瞅先。

**Comment by Minamtt** [comment]
感谢关注Issue。效果见http://106.54.45.63:2013。（可能需要等待一段时间才能呈现出动画）

**Comment by Barrior** [comment]
> > 是在原来 Particle 特效上增加粒子的随机旋转，还是新增一个这样的特效？有效果图吗，简易版的也行，我瞅瞅先。
> 
> 感谢关注Issue。效果见http://106.54.45.63:2013
> 
> （可能需要等待一段时间才能呈现出动画）

明白了，挺好的效果，我记录一下，后面找点时间把它加上，再通知你哦。

**Comment by Barrior** [comment]
@Minamtt 粒子自旋效果已经支持了，可以安装最新版体验哟，API见官方文档：https://jparticles.js.org/#/examples/particle
